name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install Flutter dependencies
      - run: flutter pub get

      # Create Podfile if missing
      - name: Generate Podfile if missing
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "platform :ios, '11.0'" > ios/Podfile
            echo "target 'Runner' do" >> ios/Podfile
            echo "  use_frameworks!" >> ios/Podfile
            echo "  # Add your dependencies here" >> ios/Podfile
            echo "end" >> ios/Podfile
          fi

      # Update CocoaPods repository
      - run: pod repo update
        working-directory: ios

      # Install CocoaPods dependencies
      - run: pod install --project-directory=ios

      # Build iOS app for release (no code signing)
      - run: flutter build ios --release --no-codesign

      # Prepare for IPA export
      - run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      # Move the built Runner.app to Payload
      - run: mv Runner.app/ Payload/
        working-directory: build/ios/iphoneos

      # Zip the output IPA
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
