name: iOS Production Build

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (semver format)'
        required: true
        default: '1.0.0'

env:
  FLUTTER_VERSION: '3.19.5'  # Latest stable as of 2024-05-23
  XCODE_VERSION: '15.3'      # Match your project's requirements

jobs:
  build-and-sign-ios:
    name: 🚀 iOS Production Build & Sign
    runs-on: macos-latest
    environment: production
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          architecture: x64

      - name: Setup Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ios/Pods
            ios/.symlinks
            ios/Flutter/Flutter.podspec
            .flutter-plugins
            .flutter-plugins-dependencies
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock', 'ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: |
          flutter pub get
          cd ios && pod install --repo-update

      - name: Set build version
        run: |
          # Extract version from pubspec.yaml
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d+ -f1)
          BUILD_NUMBER=${{ github.run_number }}
          
          # Update iOS project version
          cd ios
          agvtool new-marketing-version $VERSION
          agvtool new-version -all $BUILD_NUMBER

      - name: Import Code Signing
        uses: apple-actions/import-code-sign-identities@v1
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}

      - name: Install Provisioning Profile
        uses: apple-actions/install-provisioning-profile@v1
        with:
          profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}

      - name: Build iOS (Release)
        run: |
          flutter build ios --release --dart-define=APP_ENV=production
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            clean archive

      - name: Package and Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath ios/build/ipa

      - name: Validate IPA
        run: |
          if [ ! -f "ios/build/ipa/Runner.ipa" ]; then
            echo "❌ IPA file not found!"
            exit 1
          fi
          echo "✅ IPA file verified"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-ipa-${{ github.run_number }}
          path: ios/build/ipa/Runner.ipa
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: v${{ inputs.release-version }}+${{ github.run_number }}
          name: Production Build v${{ inputs.release-version }} (${{ github.run_number }})
          body: |
            Production iOS Build
            - Commit: ${{ github.sha }}
            - Build Number: ${{ github.run_number }}
            - Flutter Version: ${{ env.FLUTTER_VERSION }}
          files: ios/build/ipa/Runner.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}