name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install Flutter dependencies
      - run: flutter pub get

      # Create the RunnerTests directory and add the RunnerTests.swift file
      - name: Create RunnerTests directory and add RunnerTests.swift
        run: |
          mkdir -p ios/RunnerTests
          echo 'import Flutter' > ios/RunnerTests/RunnerTests.swift
          echo 'import UIKit' >> ios/RunnerTests/RunnerTests.swift
          echo 'import XCTest' >> ios/RunnerTests/RunnerTests.swift
          echo '' >> ios/RunnerTests/RunnerTests.swift
          echo 'class RunnerTests: XCTestCase {' >> ios/RunnerTests/RunnerTests.swift
          echo '' >> ios/RunnerTests/RunnerTests.swift
          echo '  func testExample() {' >> ios/RunnerTests/RunnerTests.swift
          echo '    // If you add code to the Runner application, consider adding tests here.' >> ios/RunnerTests/RunnerTests.swift
          echo '    // See https://developer.apple.com/documentation/xctest for more information about using XCTest.' >> ios/RunnerTests/RunnerTests.swift
          echo '  }' >> ios/RunnerTests/RunnerTests.swift
          echo '' >> ios/RunnerTests/RunnerTests.swift
          echo '}' >> ios/RunnerTests/RunnerTests.swift

      # Install CocoaPods dependencies
      - run: pod install --project-directory=ios

      # Build iOS app for release
      - run: flutter build ios --release --no-codesign

      # Prepare for IPA export
      - run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      # Move the .app file to Payload folder
      - run: |
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            mv build/ios/iphoneos/Runner.app Payload/
          else
            echo "Error: Runner.app not found!"
            exit 1
          fi
        working-directory: build/ios/iphoneos

      # Zip the output IPA
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the IPA to GitHub release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
