name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      # Check if the certificate and provisioning profile exist before proceeding
      - name: Check if certificate and provisioning profile exist
        run: |
          if [ ! -f ios/keys/certificate.p12 ]; then
            echo "Error: certificate.p12 not found in ios/keys"
            exit 1
          fi
          if [ ! -f ios/keys/provisioning_profile.mobileprovision ]; then
            echo "Error: provisioning_profile.mobileprovision not found in ios/keys"
            exit 1
          fi
          echo "Both certificate and provisioning profile are found. Proceeding with build."
        shell: bash

      # Decrypt the certificate and provisioning profile if needed (if stored as secrets)
      # Copy to the ios/keys folder
      - name: Copy certificate and provisioning profile
        run: |
          mkdir -p ios/keys
          echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > ios/keys/certificate.p12
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ios/keys/provisioning_profile.mobileprovision
        shell: bash

      # Create and configure the keychain
      - name: Create and configure keychain
        run: |
          security create-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "" build.keychain
        shell: bash

      # Import the certificate into the keychain
      - name: Import certificate
        run: |
          security import ios/keys/certificate.p12 -k build.keychain -P ${{ secrets.CERT_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -d user -s build.keychain
          security set-keychain-settings build.keychain
        shell: bash

      # Set up the provisioning profile
      - name: Set up provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios/keys/provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        shell: bash

      # Build iOS release with code signing
      - run: flutter build ios --release
        env:
          CI: true

      # Create Payload directory and move the built app
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Zip the output .ipa file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the .ipa file to the release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
