name: Suellas Rewards

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 Suellas Rewards
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Create .ipa file
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/ios/iphoneos/Runner.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/ios/iphoneos/Runner.xcarchive \
            -exportPath $PWD/build/ios/iphoneos \
            -exportOptionsPlist ios/ExportOptions.plist

      - name: Zip .ipa for testing
        run: zip -qq -r -9 SuellasRewards.ipa.zip build/ios/iphoneos/Runner.ipa

      - name: Upload .ipa zip for testing
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/SuellasRewards.ipa.zip
          tag: v1.0
          overwrite: true
          body: "This is the first release .ipa for testing"
