name: Deploy iOS App to App Store

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "🚀 Deploy to App Store"
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: brew install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download IPA from Latest Release
        run: |
          gh release download -p "FlutterIpaExport.ipa" -O FlutterIpaExport.ipa || { echo "❌ IPA not found!"; exit 1; }

      - name: Create Fastlane Directory
        run: mkdir -p ios/fastlane

      - name: Install Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Set Up Fastlane
        run: |
          cd ios
          bundle init
          echo 'gem "fastlane"' >> Gemfile
          bundle install
          mkdir -p fastlane
          echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" | base64 --decode > fastlane/AuthKey.p8
          ls -l fastlane/AuthKey.p8  # Debugging: Check if file exists
          echo "APP_STORE_CONNECT_API_PRIVATE_KEY_PATH=$GITHUB_WORKSPACE/ios/fastlane/AuthKey.p8" >> $GITHUB_ENV

      - name: Configure Fastlane
        run: |
          cat <<EOF > ios/fastlane/Fastfile
          default_platform(:ios)

          platform :ios do
            desc "Push a new release build to the App Store"
            lane :release do
              upload_to_app_store(
                api_key: {
                  key_id: "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}",
                  issuer_id: "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}",
                  key_file: ENV["APP_STORE_CONNECT_API_PRIVATE_KEY_PATH"]
                },
                app_identifier: "${{ secrets.APP_IDENTIFIER }}"
              )
            end
          end
          EOF

      - name: Install Fastlane Dependencies
        run: |
          cd ios
          bundle install

      - name: Upload IPA to App Store
        run: |
          echo "🔍 Checking API Key Environment Variables..."
          echo "APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID"
          echo "APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID"
          echo "APP_STORE_CONNECT_API_PRIVATE_KEY_PATH: $APP_STORE_CONNECT_API_PRIVATE_KEY_PATH"
          
          if [ ! -f "$APP_STORE_CONNECT_API_PRIVATE_KEY_PATH" ]; then
            echo "❌ Private key file not found at $APP_STORE_CONNECT_API_PRIVATE_KEY_PATH!"
            exit 1
          fi

          cd ios
          bundle exec fastlane release || { echo "❌ Fastlane upload failed!"; exit 1; }
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_PRIVATE_KEY_PATH: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY_PATH }}
          FASTLANE_OPT_OUT_USAGE: true

      - name: Complete job
        run: echo "✅ Deployment Completed Successfully"
