name: Deploy iOS App to App Store

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy to App Store
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: brew install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download IPA from Latest Release
        run: gh release download -p "FlutterIpaExport.ipa" -O FlutterIpaExport.ipa

      - name: Create Fastlane Directory
        run: mkdir -p ios/fastlane

      - name: Install Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Create Gemfile
        run: |
          echo 'source "https://rubygems.org"' > ios/Gemfile
          echo 'gem "fastlane"' >> ios/Gemfile
          echo 'gem "logger"' >> ios/Gemfile
          echo 'gem "mutex_m"' >> ios/Gemfile
          echo 'gem "abbrev"' >> ios/Gemfile
          echo 'gem "ostruct"' >> ios/Gemfile

      - name: Install Fastlane Dependencies
        run: bundle install
        working-directory: ios

      - name: Initialize Fastlane
        run: bundle exec fastlane init
        working-directory: ios
        env:
          FASTLANE_OPT_OUT_USAGE: true

      - name: Upload IPA to App Store
        run: bundle exec fastlane release
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          FASTLANE_OPT_OUT_USAGE: true

      - name: Complete job
        run: echo "Job Completed"
