name: Deploy iOS App to App Store

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy to App Store
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Built IPA
        uses: actions/download-artifact@v4  # ✅ Updated to v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos

      - name: Install Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Fastlane Dependencies
        run: bundle install
        working-directory: ios

      - name: Upload IPA to App Store
        run: bundle exec fastlane release
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
