on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "🚀 Deploy to App Store"
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: brew install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download IPA from Latest Release
        run: |
          gh release download -p "FlutterIpaExport.ipa" -O FlutterIpaExport.ipa || { echo "❌ IPA not found!"; exit 1; }

      - name: Create Fastlane Directory
        run: mkdir -p ios/fastlane

      - name: Install Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Set Up Fastlane
        run: |
          cd ios
          bundle init
          echo 'gem "fastlane"' >> Gemfile
          bundle install

      - name: Create AuthKey.p8 from Secret
        run: |
          mkdir -p ios
          echo "${{ secrets.APPSTORE_AUTH_KEY }}" > ios/AuthKey.p8
          chmod 600 ios/AuthKey.p8

      - name: Configure Fastlane
        run: |
          cat <<EOF > ios/fastlane/Fastfile
          default_platform(:ios)
          key = File.read('/Users/runner/work/suellasrewards/suellasrewards/ios/AuthKey.p8')

          platform :ios do
            desc "Push a new release build to the App Store"
            lane :release do
              upload_to_app_store(
                api_key: {
                  key_id: "C955KM32VK",
                  issuer_id: "6ea64670-374c-432a-ae26-2e54ddc66ed8",
                  key: key
                },
                app_identifier: "com.suellas.rewards",
                ipa: "../FlutterIpaExport.ipa"
              )
            end
          end
          EOF

      - name: Install Fastlane Dependencies
        run: |
          cd ios
          bundle install

      - name: Upload IPA to App Store
        run: |
          echo "🔍 Checking Environment Variables..."
          echo "KEY ID: $APP_STORE_CONNECT_API_KEY_ID"
          echo "ISSUER ID: $APP_STORE_CONNECT_ISSUER_ID"
          
          cd ios
          bundle exec fastlane release || { echo "❌ Fastlane upload failed!"; exit 1; }
        env:
          APP_STORE_CONNECT_API_KEY_ID: C955KM32VK
          APP_STORE_CONNECT_ISSUER_ID: 6ea64670-374c-432a-ae26-2e54ddc66ed8
          FASTLANE_OPT_OUT_USAGE: true

      - name: Complete job
        run: echo "✅ Deployment Completed Successfully"