name: Deploy iOS App to App Store

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy to App Store
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: brew install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status

      - name: Download IPA from Latest Release
        run: gh release download -p "FlutterIpaExport.ipa" -O FlutterIpaExport.ipa

      - name: Set Up Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install fastlane -NV
          bundle install
        working-directory: ios

      - name: Ensure Fastlane Directory Exists
        run: mkdir -p ios/fastlane

      - name: Write App Store API Private Key
        run: echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" | base64 --decode > ios/AuthKey.p8

      - name: Upload IPA to App Store
        run: bundle exec fastlane release
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_PRIVATE_KEY_PATH: ios/AuthKey.p8
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}

      - name: Cleanup API Key File
        if: always()
        run: rm -f ios/AuthKey.p8

      - name: Complete Job
        run: echo "✅ Deployment Complete"
